version: '3'
services:
  db:
    build: .
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./work:/var/lib/postgresql/work
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
        - db_network
  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmindata:/var/lib/pgadmin4/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: root@example.com
      PGADMIN_DEFAULT_PASSWORD: root
      TZ: Asia/Tokyo
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      - db_network
networks:
  db_network:
volumes:
  postgres-data:
  pgadmindata:
