version: '3'
services:
  db:
    build: .
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./work:/var/lib/postgresql/work
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
